### PR TITLE
created new branch "singleProduct" and store/singleProduct.js

### PR DESCRIPTION
**Pull request by siyunfeng**
still need to work on some of the thunk functions

### CODE REVIEW

**Comment by alliebug** [comment]
i'm not sure if we should have delete_product in the singleProduct reducer or in the products reducer

**Comment by siyunfeng** [comment]
> 

We will need the delete_product later for admin but for now we can ignore it

**Review by christine-zheng — CHANGES_REQUESTED** [review]
initial state to be {} since findOne / findByPk returns an object

**Review by christine-zheng — APPROVED** [review]
for /api/products.js -- we may need to use res.json instead of res.send.
- i think res.send should also work, so approving for now.

**Pull request merged**
